// Single definition of how the plugin bundle is built — shared by build-bundle
// and check-bundle so the two can never drift apart (the same lesson as the one
// isKnowledge/isStale definition).
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { BuildOptions } from "esbuild";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/**
 * The committed artifact the Claude Code plugin runs.
 *
 * `.mjs` is deliberate: the output is ESM, and Node only treats a `.js` file as
 * ESM when a nearby package.json says `"type": "module"`. A self-contained bundle
 * must not depend on a neighbouring manifest, so pin the extension instead.
 */
export const BUNDLE_OUT = join(ROOT, "bundle", "plugin-server.mjs");

export const bundleOptions: BuildOptions = {
  entryPoints: [join(ROOT, "src", "plugin-stdio.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  // Keep the heavy semantic stack out of the bundle. Nothing on the lexical path
  // imports it (embed.ts is lazy-loaded and unreachable here); this is a guard so
  // an accidental import fails loudly at build time instead of bloating the plugin.
  external: ["@huggingface/transformers"],
  banner: {
    js: "// GENERATED by `npm run build:bundle` from src/plugin-stdio.ts — do not edit.",
  },
};
